In [1]:
import os
os.getcwd()

'/Users/txj92/Desktop/epilepsy-rnaseq-ml/notebooks'

In [2]:
import pandas as pd
import gzip
import numpy as np

In [3]:
counts = pd.read_csv(
    "../data/raw/GSE256068_raw_counts_GRCh38.p13_NCBI.tsv.gz",
    sep="\t",
    compression="gzip"
)

counts.head()

,GeneID,GSM8084969,GSM8084970,GSM8084971,GSM8084972,GSM8084973,GSM8084974,GSM8084975,GSM8084976,GSM8084978,...,GSM8085120,GSM8085121,GSM8085123,GSM8085124,GSM8085125,GSM8085126,GSM8085127,GSM8085128,GSM8085129,GSM8085130
0,100287102,1,2,3,3,2,1,2,3,1,...,1,1,2,2,3,5,4,3,2,0
1,653635,656,770,541,912,491,814,812,861,823,...,1065,1387,1066,1666,908,1124,955,657,671,643
2,102466751,25,21,14,20,19,28,21,26,18,...,44,62,25,106,30,83,23,32,26,20
3,107985730,6,6,3,4,1,5,1,1,3,...,3,1,3,2,2,1,4,0,0,3
4,100302278,1,0,1,0,0,1,0,0,0,...,0,0,0,1,1,0,1,0,0,0

In [4]:
with gzip.open(
    "../data/raw/GSE256068_series_matrix.txt.gz",
    "rt"
) as f:
    for i in range(40):
        print(f.readline())

!Series_title	"Identification of gene regulatory networks affected across drug-resistant epilepsies"

!Series_geo_accession	"GSE256068"

!Series_status	"Public on Mar 12 2024"

!Series_submission_date	"Feb 19 2024"

!Series_last_update_date	"Mar 21 2024"

!Series_pubmed_id	"38467626"

!Series_summary	"Epilepsy is a chronic and heterogenous disease characterized by recurrent unprovoked seizures, that are commonly resistant to antiseizure medications. This study applies a transcriptome network-based approach across epilepsies aiming to improve understanding of molecular disease pathobiology, recognize affected biological mechanisms and apply causal reasoning to identify therapeutic hypotheses. This study included the most common drug-resistant epilepsies (DREs), such as temporal lobe epilepsy with hippocampal sclerosis (TLE-HS), and mTOR pathway-related malformations of cortical development (mTORopathies). This systematic comparison characterized the global molecular signature of epilepsies, elucidating the key underlying mechanisms of disease pathology including neurotransmission and synaptic plasticity, brain extracellular matrix and energy metabolism. In addition, specific dysregulations in neuroinflammation and oligodendrocyte function were observed in TLE-HS and mTORopathies, respectively. The aforementioned mechanisms are proposed as molecular hallmarks of DRE with the identified upstream regulators offering opportunities for drug-target discovery and development."

!Series_overall_design	"Bulk RNA-seq of four epilepsy pathologies (TLE-HS, FCD IIa, FCD Iib, TSC) and matching control cortex and hippocampal samples"

!Series_type	"Expression profiling by high throughput sequencing"

!Series_contributor	"Liesbeth,,François"

!Series_contributor	"Alessia,,Romagnolo"

!Series_contributor	"Eleonora,,Aronica"

!Series_contributor	"Stefanie,,Dedeurwaerdere"

!Series_sample_id	"GSM8084969 GSM8084970 GSM8084971 GSM8084972 GSM8084973 GSM8084974 GSM8084975 GSM8084976 GSM8084977 GSM8084978 GSM8084979 GSM8084980 GSM8084981 GSM8084982 GSM8084983 GSM8084984 GSM8084985 GSM8084986 GSM8084987 GSM8084988 GSM8084989 GSM8084990 GSM8084991 GSM8084992 GSM8084993 GSM8084994 GSM8084995 GSM8084996 GSM8084997 GSM8084998 GSM8084999 GSM8085000 GSM8085001 GSM8085002 GSM8085003 GSM8085004 GSM8085005 GSM8085006 GSM8085007 GSM8085008 GSM8085009 GSM8085010 GSM8085011 GSM8085012 GSM8085013 GSM8085014 GSM8085015 GSM8085016 GSM8085017 GSM8085018 GSM8085019 GSM8085020 GSM8085021 GSM8085022 GSM8085023 GSM8085024 GSM8085025 GSM8085026 GSM8085027 GSM8085028 GSM8085029 GSM8085030 GSM8085031 GSM8085032 GSM8085033 GSM8085034 GSM8085035 GSM8085036 GSM8085037 GSM8085038 GSM8085039 GSM8085040 GSM8085041 GSM8085042 GSM8085043 GSM8085044 GSM8085045 GSM8085046 GSM8085047 GSM8085048 GSM8085049 GSM8085050 GSM8085051 GSM8085052 GSM8085053 GSM8085054 GSM8085055 GSM8085056 GSM8085057 GSM8085058 GSM8085059 GSM8085060 GSM8085061 GSM8085062 GSM8085063 GSM8085064 GSM8085065 GSM8085066 GSM8085067 GSM8085068 GSM8085069 GSM8085070 GSM8085071 GSM8085072 GSM8085073 GSM8085074 GSM8085075 GSM8085076 GSM8085077 GSM8085078 GSM8085079 GSM8085080 GSM8085081 GSM8085082 GSM8085083 GSM8085084 GSM8085085 GSM8085086 GSM8085087 GSM8085088 GSM8085089 GSM8085090 GSM8085091 GSM8085092 GSM8085093 GSM8085094 GSM8085095 GSM8085096 GSM8085097 GSM8085098 GSM8085099 GSM8085100 GSM8085101 GSM8085102 GSM8085103 GSM8085104 GSM8085105 GSM8085106 GSM8085107 GSM8085108 GSM8085109 GSM8085110 GSM8085111 GSM8085112 GSM8085113 GSM8085114 GSM8085115 GSM8085116 GSM8085117 GSM8085118 GSM8085119 GSM8085120 GSM8085121 GSM8085122 GSM8085123 GSM8085124 GSM8085125 GSM8085126 GSM8085127 GSM8085128 GSM8085129 GSM8085130 "

!Series_contact_name	"Liesbeth,,François"

!Series_contact_email	"liesbeth.francois@ucb.com"

!Series_contact_institute	"UCB Pharma SA"

!Series_contact_address	"Allée de la Recherche 60"

!Series_contact_city	"Brussels"

!Series_contact_state	"Brussels"

!Series_contact_zip/postal_code	"1170"

!Series_contact_country	"Belgium"

!Series_supplementary_file	"ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE256nnn/GSE256068/suppl/GSE256068_processed_data.csv.gz"

!Series_supplementary_file	"ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE256nnn/GSE256068/suppl/GSE256068_raw_data.csv.gz"

!Series_platform_id	"GPL24676"

!Series_platform_taxid	"9606"

!Series_sample_taxid	"9606"

!Series_relation	"BioProject: https://www.ncbi.nlm.nih.gov/bioproject/PRJNA1077986"



!Sample_title	"TSC_1"	"TSC_2"	"FCD2a_1"	"FCD2a_2"	"ControlCortex_1"	"ControlCortex_2"	"TSC_3"	"FCD2a_3"	"TSC_4"	"TSC_5"	"ControlCortex_3"	"FCD2a_4"	"TSC_6"	"TSC_7"	"TSC_8"	"FCD2a_5"	"FCD2b_1"	"FCD2b_2"	"ControlCortex_4"	"TLE-HS_1"	"TLE-HS_2"	"TLE-HS_3"	"ControlHippocampus_1"	"FCD2a_6"	"FCD2b_3"	"FCD2b_4"	"TSC_9"	"ControlCortex_5"	"ControlCortex_6"	"TSC_10"	"TSC_11"	"ControlCortex_7"	"TSC_12"	"TLE-HS_4"	"FCD2a_7"	"ControlCortex_8"	"ControlCortex_9"	"TLE-HS_5"	"FCD2b_5"	"TLE-HS_6"	"ControlHippocampus_2"	"FCD2b_6"	"ControlCortex_10"	"FCD2b_7"	"TLE-HS_7"	"TLE-HS_8"	"TSC_13"	"TLE-HS_9"	"FCD2b_8"	"ControlHippocampus_3"	"FCD2b_9"	"TLE-HS_10"	"TLE-HS_11"	"TLE-HS_12"	"TLE-HS_13"	"FCD2b_10"	"FCD2b_11"	"FCD2a_8"	"TLE-HS_14"	"FCD2a_9"	"FCD2a_10"	"FCD2b_12"	"ControlCortex_11"	"TSC_14"	"TLE-HS_15"	"ControlHippocampus_4"	"FCD2b_13"	"ControlHippocampus_5"	"TSC_15"	"TLE-HS_16"	"TLE-HS_17"	"FCD2b_14"	"TLE-HS_18"	"TLE-HS_19"	"TLE-HS_20"	"FCD2b_15"	"FCD2b_16"	"TLE-HS_21"	"FCD2b_17"	"ControlHippocampus_6"	"TLE-HS_22"	"TLE-HS_23"	"TLE-HS_24"	"TLE-HS_25"	"TLE-HS_26"	"TLE-HS_27"	"TLE-HS_28"	"TLE-HS_29"	"ControlCortex_12"	"TSC_16"	"TLE-HS_30"	"TSC_17"	"TLE-HS_31"	"TLE-HS_32"	"TLE-HS_33"	"FCD2b_18"	"TLE-HS_34"	"TLE-HS_35"	"ControlHippocampus_7"	"FCD2b_19"	"TLE-HS_36"	"TLE-HS_37"	"TLE-HS_38"	"TLE-HS_39"	"TLE-HS_40"	"FCD2b_20"	"FCD2b_21"	"TLE-HS_41"	"TLE-HS_42"	"TLE-HS_43"	"TLE-HS_44"	"FCD2a_11"	"ControlHippocampus_8"	"FCD2b_22"	"TLE-HS_45"	"FCD2a_12"	"FCD2b_23"	"TLE-HS_46"	"TLE-HS_47"	"ControlCortex_13"	"TSC_18"	"TLE-HS_48"	"TLE-HS_49"	"TSC_19"	"FCD2a_13"	"TLE-HS_50"	"TLE-HS_51"	"TLE-HS_52"	"TLE-HS_53"	"TLE-HS_54"	"TSC_20"	"FCD2b_24"	"TLE-HS_55"	"TLE-HS_56"	"ControlHippocampus_9"	"TLE-HS_57"	"TLE-HS_58"	"TLE-HS_59"	"FCD2a_14"	"ControlCortex_14"	"TLE-HS_60"	"TLE-HS_61"	"TLE-HS_62"	"FCD2b_25"	"FCD2a_15"	"FCD2b_26"	"TLE-HS_63"	"FCD2b_27"	"TSC_21"	"FCD2b_28"	"FCD2b_29"	"FCD2b_30"	"FCD2a_16"	"FCD2b_31"	"FCD2b_32"	"FCD2a_17"	"TLE-HS_64"	"ControlHippocampus_10"	"ControlHippocampus_11"	"ControlHippocampus_12"	"ControlHippocampus_13"	"FCD2b_33"

!Sample_geo_accession	"GSM8084969"	"GSM8084970"	"GSM8084971"	"GSM8084972"	"GSM8084973"	"GSM8084974"	"GSM8084975"	"GSM8084976"	"GSM8084977"	"GSM8084978"	"GSM8084979"	"GSM8084980"	"GSM8084981"	"GSM8084982"	"GSM8084983"	"GSM8084984"	"GSM8084985"	"GSM8084986"	"GSM8084987"	"GSM8084988"	"GSM8084989"	"GSM8084990"	"GSM8084991"	"GSM8084992"	"GSM8084993"	"GSM8084994"	"GSM8084995"	"GSM8084996"	"GSM8084997"	"GSM8084998"	"GSM8084999"	"GSM8085000"	"GSM8085001"	"GSM8085002"	"GSM8085003"	"GSM8085004"	"GSM8085005"	"GSM8085006"	"GSM8085007"	"GSM8085008"	"GSM8085009"	"GSM8085010"	"GSM8085011"	"GSM8085012"	"GSM8085013"	"GSM8085014"	"GSM8085015"	"GSM8085016"	"GSM8085017"	"GSM8085018"	"GSM8085019"	"GSM8085020"	"GSM8085021"	"GSM8085022"	"GSM8085023"	"GSM8085024"	"GSM8085025"	"GSM8085026"	"GSM8085027"	"GSM8085028"	"GSM8085029"	"GSM8085030"	"GSM8085031"	"GSM8085032"	"GSM8085033"	"GSM8085034"	"GSM8085035"	"GSM8085036"	"GSM8085037"	"GSM8085038"	"GSM8085039"	"GSM8085040"	"GSM8085041"	"GSM8085042"	"GSM8085043"	"GSM8085044"	"GSM8085045"	"GSM8085046"	"GSM8085047"	"GSM8085048"	"GSM8085049"	"GSM8085050"	"GSM8085051"	"GSM8085052"	"GSM8085053"	"GSM8085054"	"GSM8085055"	"GSM8085056"	"GSM8085057"	"GSM8085058"	"GSM8085059"	"GSM8085060"	"GSM8085061"	"GSM8085062"	"GSM8085063"	"GSM8085064"	"GSM8085065"	"GSM8085066"	"GSM8085067"	"GSM8085068"	"GSM8085069"	"GSM8085070"	"GSM8085071"	"GSM8085072"	"GSM8085073"	"GSM8085074"	"GSM8085075"	"GSM8085076"	"GSM8085077"	"GSM8085078"	"GSM8085079"	"GSM8085080"	"GSM8085081"	"GSM8085082"	"GSM8085083"	"GSM8085084"	"GSM8085085"	"GSM8085086"	"GSM8085087"	"GSM8085088"	"GSM8085089"	"GSM8085090"	"GSM8085091"	"GSM8085092"	"GSM8085093"	"GSM8085094"	"GSM8085095"	"GSM8085096"	"GSM8085097"	"GSM8085098"	"GSM8085099"	"GSM8085100"	"GSM8085101"	"GSM8085102"	"GSM8085103"	"GSM8085104"	"GSM8085105"	"GSM8085106"	"GSM8085107"	"GSM8085108"	"GSM8085109"	"GSM8085110"	"GSM8085111"	"GSM8085112"	"GSM8085113"	"GSM8085114"	"GSM8085115"	"GSM8085116"	"GSM8085117"	"GSM8085118"	"GSM8085119"	"GSM8085120"	"GSM8085121"	"GSM8085122"	"GSM8085123"	"GSM8085124"	"GSM8085125"	"GSM8085126"	"GSM8085127"	"GSM8085128"	"GSM8085129"	"GSM8085130"

!Sample_status	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"	"Public on Mar 12 2024"

!Sample_submission_date	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"	"Feb 19 2024"

!Sample_last_update_date	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"	"Mar 12 2024"

!Sample_type	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"

!Sample_channel_count	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"


In [5]:
counts.head()

,GeneID,GSM8084969,GSM8084970,GSM8084971,GSM8084972,GSM8084973,GSM8084974,GSM8084975,GSM8084976,GSM8084978,...,GSM8085120,GSM8085121,GSM8085123,GSM8085124,GSM8085125,GSM8085126,GSM8085127,GSM8085128,GSM8085129,GSM8085130
0,100287102,1,2,3,3,2,1,2,3,1,...,1,1,2,2,3,5,4,3,2,0
1,653635,656,770,541,912,491,814,812,861,823,...,1065,1387,1066,1666,908,1124,955,657,671,643
2,102466751,25,21,14,20,19,28,21,26,18,...,44,62,25,106,30,83,23,32,26,20
3,107985730,6,6,3,4,1,5,1,1,3,...,3,1,3,2,2,1,4,0,0,3
4,100302278,1,0,1,0,0,1,0,0,0,...,0,0,0,1,1,0,1,0,0,0

In [6]:
counts.shape

(39376, 145)

In [7]:
counts.columns[:10]

Index(['GeneID', 'GSM8084969', 'GSM8084970', 'GSM8084971', 'GSM8084972',
       'GSM8084973', 'GSM8084974', 'GSM8084975', 'GSM8084976', 'GSM8084978'],
      dtype='object')

In [8]:
counts = counts.set_index("GeneID")

In [9]:
counts.head()

,GSM8084969,GSM8084970,GSM8084971,GSM8084972,GSM8084973,GSM8084974,GSM8084975,GSM8084976,GSM8084978,GSM8084981,...,GSM8085120,GSM8085121,GSM8085123,GSM8085124,GSM8085125,GSM8085126,GSM8085127,GSM8085128,GSM8085129,GSM8085130
GeneID,,,,,,,,,,,,,,,,,,,,,
100287102,1,2,3,3,2,1,2,3,1,1,...,1,1,2,2,3,5,4,3,2,0
653635,656,770,541,912,491,814,812,861,823,998,...,1065,1387,1066,1666,908,1124,955,657,671,643
102466751,25,21,14,20,19,28,21,26,18,33,...,44,62,25,106,30,83,23,32,26,20
107985730,6,6,3,4,1,5,1,1,3,7,...,3,1,3,2,2,1,4,0,0,3
100302278,1,0,1,0,0,1,0,0,0,0,...,0,0,0,1,1,0,1,0,0,0

In [10]:
counts.shape

(39376, 144)

In [11]:
counts_t = counts.T
counts_t.head()

GeneID,100287102,653635,102466751,107985730,100302278,645520,79501,100996442,729737,102725121,...,4538,4564,4575,4568,4540,4541,4556,4519,4576,4571
GSM8084969,1,656,25,6,1,2,0,39,278,1,...,325456,286,305,544,210119,64192,7183,151954,311,2505
GSM8084970,2,770,21,6,0,0,0,73,282,5,...,197727,267,303,506,116276,31058,3015,103002,325,1157
GSM8084971,3,541,14,3,1,0,0,84,178,5,...,188747,207,214,684,90415,23571,3002,95880,271,1374
GSM8084972,3,912,20,4,0,1,0,134,120,3,...,567470,615,635,1460,326038,106882,11301,297549,1087,4000
GSM8084973,2,491,19,1,0,2,0,35,47,3,...,1252438,877,998,2736,540662,160508,17656,596416,1231,6076

In [12]:
counts_t.isna().sum().sum()

np.int64(0)

In [13]:
counts_log = np.log2(counts_t + 1)

In [14]:
counts_log.head()

GeneID,100287102,653635,102466751,107985730,100302278,645520,79501,100996442,729737,102725121,...,4538,4564,4575,4568,4540,4541,4556,4519,4576,4571
GSM8084969,1.000000,9.359750,4.700440,2.807355,1.0,1.584963,0.0,5.321928,8.124121,1.000000,...,18.312107,8.164907,8.257388,9.090112,17.680854,15.970128,12.810572,17.213285,8.285402,11.291171
GSM8084970,1.584963,9.590587,4.459432,2.807355,0.0,0.000000,0.0,6.209453,8.144658,2.584963,...,17.593158,8.066089,8.247928,8.985842,16.827206,14.922724,11.558421,16.652327,8.348728,10.177420
GSM8084971,2.000000,9.082149,3.906891,2.000000,1.0,0.000000,0.0,6.409391,7.483816,2.584963,...,17.526102,7.700440,7.748193,9.419960,16.464290,14.524787,11.552189,16.548957,8.087463,10.425216
GSM8084972,2.000000,9.834471,4.392317,2.321928,0.0,1.000000,0.0,7.076816,6.918863,2.000000,...,19.114187,9.266787,9.312883,10.512740,18.314685,16.705673,13.464290,18.182773,10.087463,11.966145
GSM8084973,1.584963,8.942515,4.321928,1.000000,0.0,1.584963,0.0,5.169925,5.584963,2.000000,...,20.256309,9.778077,9.964341,11.418380,19.044370,17.292295,14.107953,19.185962,10.266787,12.569144

In [15]:
counts_log.to_csv(
    "../data/processed/log2_counts.csv",
    index=True
)

In [16]:
with gzip.open(
    "../data/raw/GSE256068_series_matrix.txt.gz",
    "rt"
) as f:
    
    lines = f.readlines()

title_line = [x for x in lines if x.startswith("!Sample_title")][0]
geo_line = [x for x in lines if x.startswith("!Sample_geo_accession")][0]

In [17]:
titles = title_line.strip().split("\t")[1:]
gsm_ids = geo_line.strip().split("\t")[1:]

In [18]:
titles[:5]

['"TSC_1"', '"TSC_2"', '"FCD2a_1"', '"FCD2a_2"', '"ControlCortex_1"']

In [19]:
gsm_ids[:5]

['"GSM8084969"',
 '"GSM8084970"',
 '"GSM8084971"',
 '"GSM8084972"',
 '"GSM8084973"']

In [20]:
metadata = pd.DataFrame({
    "sample_id": gsm_ids,
    "sample_title": titles
})

metadata["sample_id"] = metadata["sample_id"].str.replace('"', '', regex=False)
metadata["sample_title"] = metadata["sample_title"].str.replace('"', '', regex=False)

metadata.head()

    sample_id     sample_title
0  GSM8084969            TSC_1
1  GSM8084970            TSC_2
2  GSM8084971          FCD2a_1
3  GSM8084972          FCD2a_2
4  GSM8084973  ControlCortex_1

In [21]:
metadata["group"] = metadata["sample_title"].str.split("_").str[0]

metadata["binary_class"] = metadata["group"].apply(
    lambda x: "Control" if "Control" in x else "Epilepsy"
)

metadata.head()

    sample_id     sample_title          group binary_class
0  GSM8084969            TSC_1            TSC     Epilepsy
1  GSM8084970            TSC_2            TSC     Epilepsy
2  GSM8084971          FCD2a_1          FCD2a     Epilepsy
3  GSM8084972          FCD2a_2          FCD2a     Epilepsy
4  GSM8084973  ControlCortex_1  ControlCortex      Control

In [22]:
metadata["group"].value_counts()
metadata["binary_class"].value_counts()

binary_class
Epilepsy    135
Control      27
Name: count, dtype: int64

In [23]:
metadata.to_csv("../data/processed/metadata.csv", index=False)

In [25]:
len(gsm_ids)
counts.shape

(39376, 144)